version: 2.1
jobs:
  build-test-push:
    docker:
      - image: ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:deploy-tools
    environment:
      app: transaction-uploader
    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Inspect tags
          command: |
            echo export tag=${app}.${CIRCLE_BRANCH}.${CIRCLE_SHA1:0:7} > /tmp/mtp-env.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            source /tmp/mtp-env.sh
            docker build \
              --pull --force-rm \
              --build-arg APP_GIT_COMMIT=${CIRCLE_SHA1} \
              --build-arg APP_GIT_BRANCH=${CIRCLE_BRANCH} \
              --build-arg APP_BUILD_TAG=${tag} \
              --build-arg APP_BUILD_DATE=$(date +%FT%T%z) \
              --tag ${tag} \
              .
      - run:
          name: Test docker image
          command: |
            source /tmp/mtp-env.sh
            docker run \
              --name ${app} \
              ${tag} \
              /bin/bash -c 'pip3 install -r requirements/jenkins.txt && nosetests --with-xunit --xunit-file=/tmp/junit.xml'
            mkdir -p /tmp/reports/${app}
            docker cp ${app}:/tmp/junit.xml /tmp/reports/${app}/
            docker rm ${app}
      - store_artifacts:
          path: /tmp/reports
      - store_test_results:
          path: /tmp/reports
      - run:
          name: Push docker image
          command: |
            source /tmp/mtp-env.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            echo "Pushing ${tag} to ECR"
            docker tag ${tag} ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${tag}
            docker push ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${tag}
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "Pushing ${app} to ECR (acts as latest)"
              docker tag ${tag} ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${app}
              docker push ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${app}
            fi
workflows:
  version: 2
  build-test-push:
    jobs:
      - build-test-push
